"""Regenerates src/ui/glyphs.ts from the installed Material Symbols Rounded font.

Run: pip install fonttools && python3 scripts/gen-icon-glyphs.py
React Native can't use the font's ligatures everywhere, so icons are drawn by character code.
"""
from fontTools.ttLib import TTFont

FONT = 'assets/fonts/MaterialSymbolsRounded_500Medium.ttf'
cmap = TTFont(FONT).getBestCmap()
names = {}
for cp, glyph in sorted(cmap.items()):
    if cp >= 0xE000 and glyph not in names and glyph.replace('_', '').isalnum():
        names[glyph] = cp
body = ''.join(f'{n}:{cp:x},' for n, cp in sorted(names.items()))
with open('src/ui/glyphs.ts', 'w') as f:
    f.write('// GENERATED by scripts/gen-icon-glyphs.py from the Material Symbols Rounded font. Do not edit.\n')
    f.write('// Maps icon names (as on fonts.google.com/icons) to the character that draws them.\n')
    f.write(f"const RAW = '{body}';\n\n")
    f.write("export const GLYPHS: Record<string, string> = {};\n")
    f.write("for (const pair of RAW.split(',')) {\n  if (!pair) continue;\n  const [name, hex] = pair.split(':');\n  GLYPHS[name] = String.fromCodePoint(parseInt(hex, 16));\n}\n")
print(len(names), 'icons')
